import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from '@nativescript/angular';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { TopBarComponent } from '@src/top-bar/top-bar.component';
import { HomePageComponent } from '@src/home-page/home-page.component';
import { ContactPageComponent } from '@src/contact-page/contact-page.component';
import { CartPageComponent } from '@src/cart-page/cart-page.component';
import { ProductDetailsComponent } from '@src/product-details/product-details.component';
import { ProductGridComponent } from '@src/product-grid/product-grid.component';
import { SearchPageComponent } from '@src/search-page/search-page.component';
import { SignInPageComponent } from '@src/sign-in-page/sign-in-page.component';


// Uncomment and add to NgModule imports if you need to use two-way binding and/or HTTP wrapper
// import { NativeScriptFormsModule, NativeScriptHttpClientModule } from '@nativescript/angular';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    TopBarComponent,
    HomePageComponent,
    ContactPageComponent,
    CartPageComponent,
    ProductDetailsComponent,
    ProductGridComponent,
    SearchPageComponent,
    SignInPageComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
